grades/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^import_grades$',
        views.import_edx_gradebook,
        name='import_edx_gradebook'),

    url(r'^display-grade/(?P<user_ID>.+)/(?P<course>.+)$',
        views.display_grade,
        name='display_grade')
]

peer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('review.urls')),
    url(r'groups/', include('groups.urls')),
    url(r'grades/', include('grades.urls')),
    url(r'keyterms/', include('keyterms.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grades/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from review.models import Course, Person

@python_2_unicode_compatible
class GradeBook(models.Model):
    """
    A gradebook for a course.
    """
    course = models.ForeignKey(Course)
    passing_value = models.DecimalField(max_digits=5, decimal_places=2,
                                        help_text="A value between 0 and 100.")
    max_score = models.DecimalField(max_digits=5, decimal_places=2, default=100,
        help_text="A value between 0 and 100. Normally this is 100.0")
    last_updated = models.DateTimeField()
    def __str__(self):
        return 'Gradebook: {0} [{1}/{2}]'.format(self.course,
                                                 self.passing_value,
                                                 self.max_score)

# Our models for the phases uses ideas from:
# https://docs.djangoproject.com/en/1.10/topics/db/models/#model-inheritance
@python_2_unicode_compatible
class GradeCategory(models.Model):
    """
    A category contains one or more GradeItems. A gradebook consists of
    GradeCategories.
    A GradeItem must be a child of GradeCategory, which is a child of the
    Gradebook.
    """
    class Meta:
        verbose_name = 'Grade Category'
        verbose_name_plural = 'Grade Categories'

    gradebook = models.ForeignKey(GradeBook)
    order = models.PositiveSmallIntegerField(
        help_text="Which column order is this item")
    display_name = models.CharField(max_length=250, default='Assignment ...')
    max_score = models.DecimalField(max_digits=5, decimal_places=2, default=100,
        help_text="The largest value a student can achieve for this item")
    weight = models.DecimalField(max_digits=4, decimal_places=3,
            help_text='The weight of this item; a value between 0.0 and 1.0')
    spread_evenly = models.BooleanField(default=True,
        help_text=("Spread weight across all items evenly. True: no need to "
                   "specify weights on the GradeItems. "))

    def __str__(self):
        return '{0}. Category: {1} [wt={2}%]'.format(self.order,
                                                    self.display_name,
                                                    self.weight*100)

@python_2_unicode_compatible
class GradeItem(models.Model):
    """
    An item in the gradebook. Each gradebook consists of one or more items
    (columns) in the gradebook.
    """
    category = models.ForeignKey(GradeCategory, blank=True, null=True)
    order = models.PositiveSmallIntegerField(
        help_text="Which column order is this item")
    display_name = models.CharField(max_length=250, default='Assignment ...')
    max_score = models.DecimalField(max_digits=5, decimal_places=2, default=100,
        help_text="The largest value a student can achieve for this item")
    link = models.CharField(max_length=600, blank=True,
           help_text=("The link to the page where the student can complete "
                      "this; begin link after the base URL: /courseware/..."))
    weight = models.DecimalField(max_digits=4, decimal_places=3, default=-1.0,
                                 blank=True,
            help_text=('The weight of this item; a value between 0.0 and 1.0. '
                    'If weight=-1.0, then the weight is determined by the '
                    'category, which will assign equal weight to all items.'))
    droppable = models.BooleanField(default=False)


    def __str__(self):
        return '{0}. Category: {1}'.format(self.order,
                                           self.display_name)


@python_2_unicode_compatible
class LearnerGrade(models.Model):
    """
    A grade for the learner.
    """
    gitem = models.ForeignKey(GradeItem)
    learner = models.ForeignKey(Person)
    value = models.DecimalField(max_digits=7, decimal_places=3, blank=True,
                                null=True,
                                help_text="The grade earned by the learner.")
    not_graded_yet = models.BooleanField(default=True,
            help_text="If this item is not yet graded/submitted/etc")
    modfied_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '[{0}/{1}] for {2}'.format(self.value,
                                          self.gitem.max_score,
                                          self.learner)

review/forms.py
from django import forms
from .models import Submission

class UploadFileForm_one_file(forms.Form):

    file_upload = forms.FileField(
                widget=forms.ClearableFileInput(
                    attrs={'multiple': False,
                           'initial_text': "Please upload your submission"}))

class UploadFileForm_multiple_file(forms.Form):

    file_upload = forms.FileField(
                widget=forms.ClearableFileInput(
                    attrs={'multiple': True,
                           'initial_text': "Select 1 or more files"}))
    

class UploadFF(forms.ModelForm):

    learner_ID = forms.TextInput(attrs=None)
    class Meta:
        model= Submission
        fields = ( 'file_upload',)

grades/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt


# Our imports
from .models import GradeBook, GradeCategory, GradeItem, LearnerGrade
from review.models import Person, Course

# Python imports
import io
import csv
import six
import decimal
import datetime
from collections import defaultdict, namedtuple

# Logging
import logging
logger = logging.getLogger(__name__)

@csrf_exempt
@xframe_options_exempt
def display_grade(request, user_ID, course):
    """
    Shows the grades for a student
    """
    course = Course.objects.get(label=course)
    gradebook = course.gradebook_set.all()[0]
    learner = Person.objects.filter(user_ID=user_ID)[0]
    logger.debug('Displaying grade for {0}'.format(learner))
    grades, total_grade = get_grade_summary(learner, gradebook)
    ctx = {'course': course,
           'gradebook': gradebook,
           'grades': grades,
           'total_grade': total_grade,
           'learner': learner,
           }
    return render(request, 'grades/learner_grades.html', ctx)


def get_grade_summary(learner, gradebook):
    """
    Get the complete grade breakdown summary for a learner in a given
    ``gradebook``.

    We also return, as a second output, the grade average (total grade obtained
    so far in the course)
    """
    categories = GradeCategory.objects.filter(gradebook=gradebook)\
        .order_by('order')

    """
    How will we represent gradebook to a student? Data structure:

    [(string,decimal,{}), (string,decimal,{}), (string,decimal,{})]

    1. Outer list: holds, in order, the categories

    2. The innner tuple: holds 3 disparate elements: string, decimal, dictionary
       2a. The catogory name
       2b. The category weights (the sum of all weights should be 100%)
       2c. The dictionary* of item(s) within that category.

    3. The inner dictionaries*:
       3a. Key ('5.02', for example): indicates category 5, item 2
       3b. Value: Will be an instance of "LearnerGrade" for that item.

    * The dictionaries are sorted, just before returning and returned with:
        sorted(dict.items())  if PY3,    or    sorted(dict.iteritems()) if PY2


    To calculate the student average:
    * iterate over all the items in dictionary to calculate the score for category
    * iterate over all categories in  list, with the weight, to get overall average
    """
    grades = []
    total_grade = decimal.Decimal(0.0)
    for gcat in categories:
        items = gcat.gradeitem_set.all().order_by('order')
        if items.count() == 0:
            # No items?
            continue
        elif items.count() == 1:
            weight = max(gcat.weight, items[0].weight)
            grade = LearnerGrade.objects.filter(learner=learner, gitem=items[0])
            if grade.count() == 0:
                print('How now?')
                pass
            else:
                grades.append((gcat.display_name,
                                weight*100,
                                [('0', grade[0])]
                             ))
                if grade[0].value:
                    total_grade += weight * grade[0].value
            continue

        items_dict = {}
        item_grades = []
        item_weights = []
        category_score = decimal.Decimal(0.0)
        if gcat.spread_evenly:
            weight = decimal.Decimal(1/(items.count()+0.0))
            item_weights = [weight]*items.count()

        for idx, item in enumerate(items):
            grade = LearnerGrade.objects.filter(learner=learner, gitem=item)
            if grade.count() == 0:
                # How do we get to this point?
                item_grades.append(0.0)
                pass
            else:
                key = gcat.order + item.order/1000.0
                items_dict[key] = grade[0]
                item_weights[idx] = max(item_weights[idx], item.weight)
                if grade[0].value:
                    category_score += item_weights[idx] * grade[0].value

        # After processing all items
        total_grade += gcat.weight * category_score
        LearnerGrade_nt = namedtuple('gradeitem', ['value', 'max_score',
                                                   'not_graded_yet' ])
        items_dict[-10000] = LearnerGrade_nt(value=category_score,
                                             max_score=100,
                                             not_graded_yet=False)
        if six.PY2:
            items_dict = sorted(items_dict.iteritems())

        elif six.PY3:
            items_dict = sorted(items_dict.items())

        grades.append((gcat.display_name, gcat.weight*100, items_dict))

    return grades, total_grade

def grade_landing_page(learner, course, pr, request):
    """
    Displays the grades to the student here.
    """
    gradebook = GradeBook.objects.get(course=course)
    if learner.role == 'Admin':
        all_lgrades = LearnerGrade.objects.filter(\
                                          gitem__category__gradebook=gradebook)
        students = list(set([lgrade.learner for lgrade in all_lgrades]))

        ctx = {'learner': learner,
               'course': course,
               'pr': pr,
               'all_learners': students
               }

        return render(request, 'grades/admin_grades.html', ctx)

    else:
        return display_grade(request, learner.user_ID, course.label)



@csrf_exempt
@xframe_options_exempt
def import_edx_gradebook(request):
    """
    Allows the instructor to import a grades list from edX.

    Improvements:
    * create a "Person" profile for students that in the CSV file, but not yet
      in the DB.
    """

    logger.debug("Importing grades:")
    SKIP_FIELDS = [
        "Student ID",
        "Email",
        "Username",
        "Grade",
        "Enrollment Track",
        "Verification Status",
        "Certificate Eligible",
        "Certificate Delivered",
        "Certificate Type",
        "(Avg)",   # <--- special case: skip calculated columns
    ]

    if request.method != 'POST':
        return HttpResponse(('Grades cannot be uploaded directly. Please upload'
                             ' the grades via edX.'))

    if request.method == 'POST' and request.FILES.get('file_upload', None):
        pass
    else:
        return HttpResponse('A file was not uploaded, or a problem occurred.')

    from review.views import starting_point
    person_or_error, course, pr = starting_point(request)

    if not(isinstance(person_or_error, Person)):
        return person_or_error      # Error path if student does not exist

    learner = person_or_error
    gradebook = GradeBook.objects.get(course=course)
    if six.PY2:
        uploaded_file = request.FILES.get('file_upload').readlines()
        io_string = uploaded_file
    if six.PY3:
        uploaded_file = request.FILES.get('file_upload').read().decode('utf-8')
        io_string = io.StringIO(uploaded_file)
    logger.debug(io_string)

    out = ''
    reader = csv.reader(io_string, delimiter=',')
    columns = defaultdict(int)
    for row in reader:
        if reader.line_num == 1:
            order = 0
            for idx, col in enumerate(row):
                invalid = False
                for skip in SKIP_FIELDS:
                    if col.endswith(skip):
                        invalid = True
                if invalid:
                    order += 1
                    continue
                else:
                    columns[order] = col
                    order += 1


                cat, created_cat = GradeCategory.objects.get_or_create(
                                                    gradebook=gradebook,
                                                    display_name=col,
                                                    defaults={'order': order,
                                                              'max_score': 1,
                                                              'weight':0.0,}
                                                    )

                item, created_item = GradeItem.objects.get_or_create(
                                                display_name=col,
                                                category__gradebook=gradebook,
                                                defaults={'order': order,
                                                          'max_score': 1,
                                                          'weight':0.0,}
                                                )
                if created_cat and created_item:
                    item.category = cat
                    item.save()

            # After processing the first row
            continue

        for idx, col in enumerate(row):
            edX_id = row[0]
            email = row[1]
            display_name = row[2]
            if Person.objects.filter(email=email, role='Learn').count():
                learner = Person.objects.filter(email=email, role='Learn')[0]
            else:
                continue
                #new_student, _ = Person.objects.get_or_create(email=email,
                                                           #role='Learn',
                                                           #display_name=row[2])

            if idx not in columns.keys():
                continue

            item_name = columns[idx]
            gitem = GradeItem.objects.get(display_name=item_name,
                                          category__gradebook=gradebook)
            prior = LearnerGrade.objects.filter(gitem=gitem, learner=learner)
            if prior.count():
                item = prior[0]
            else:
                item = LearnerGrade(gitem=gitem, learner=learner)


            if col in ('Not Attempted', 'Not Available'):
                item.not_graded_yet = True
                item.value = None
            else:

grades/templates/grades/admin_grades.html
{% extends "review/base.html" %}

{% block content %}


<p>Please upload the grades CSV format, based on the export from edX:

<form action="{% url 'import_edx_gradebook' %}" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="learner_ID" value="{{learner.user_ID}}">
    <input type="hidden" name="context_id" value="{{course.label}}">
    <input type="hidden" name="resource_link_id" value="{{pr.LTI_id}}">

    <label for="id_file_upload">File upload:</label>
    <input id="id_file_upload"
    initial_text="Upload the exported gradebook" name="file_upload" type="file" multiple="" required="">
    <input type="submit" value="Upload grades" name="submit"/>
</form>

<hr>
See the grade report for these students:
<ul>
{% for student in all_learners%}
    <li><a href="{% url 'display_grade' student.user_ID course.label%}" target="_blank">{{student.display_name}}</a>
{% endfor %}


{% endblock %}

grades/templates/grades/import_grades.html
{% extends "review/base.html" %}

{% block content %}

<div class="accordion">
<h3>Click here to show/hide the extra information for instructors and TAs</h3>
<div>

<p>Please upload the grades CSV format, based on the export from edX:

<form action="{% url 'import_edx_gradebook' %}" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="learner_ID" value="{{learner.user_ID}}">
    <input type="hidden" name="context_id" value="{{course.label}}">
    <input type="hidden" name="resource_link_id" value="{{pr.LTI_id}}">

    <label for="id_file_upload">File upload:</label>
    <input id="id_file_upload"
    initial_text="Upload the exported gradebook" name="file_upload" type="file" multiple="" required="">
    <input type="submit" value="Upload grades" name="submit"/>
</form>

{% endblock %}

grades/templates/grades/learner_grades.html
{% extends "review/base.html" %}

{% block header %}
<style>
.category{
    font-size: 1.5em;
}
.final-grade{
    font-size: 1.75em;
    font-weight: bold;
}
</style>
{% endblock %}

{% block content %}

<span class="final-grade">Grade report for: {{learner.display_name}}</span>
<br>
<br>

The grades shown below are updated every 24 hours. Last update: {{gradebook.last_updated|date:"D, d F"}} at {{gradebook.last_updated|time:"H:i"}}
<br><br>
<table class="pr-admin">
<thead>
<tr>
    <th>Link to the graded item</th>
    <th>Weight</th>
    <th>Your score achieved</th>
    <th>Maximum grade possible</th>
</tr>
</thead>
{% for category, weight, items in grades %}
    {% cycle 'odd' 'even' as rowcolours silent %}
    {% if items|length > 1 %}
        {% for item in items %}
            <tr class="pr-admin-{{rowcolours}}">
            {% if forloop.first %}
                <td><span class="category">{{category}}</span></td>
                <td style="text-align:center">{{weight|floatformat}}</span></td>
                <td><span class="category" style="float:left">{%if item.1.not_graded_yet%}--{% else%}{{item.1.value|floatformat:1}}{%endif%}</span></td>
                <td><span class="category">{{item.1.max_score|floatformat}}</span></td>
              </tr>

            {% else %}
                <td>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{course.base_url}}/{{item.1.gitem.link}}" target="_blank">{{item.1.gitem.display_name}}</a></td>
                <td></td>
                <td><span style="float:right">{%if item.1.not_graded_yet%}--{% else%}{{item.1.value|floatformat:1}}{%endif%}</span></td>
                <td></td>
            {% endif %}
            </tr>

        {% endfor %}{#iterate over the items within a category#}


    {% else %}

        <tr class="pr-admin-{{rowcolours}}">
            <td><span class="category">{{category}}</span>
                <span style="float:right">(<a href="{{course.base_url}}/{{items.0.1.gitem.link}}" target="_blank">link</a>)<span></td>
            <td style="text-align:center">{{weight|floatformat}}</span></td>
            <td><span class="category" style="float:left">{%if items.0.1.not_graded_yet%}--{% else%}{{items.0.1.value|floatformat:1}}{%endif%}</span></td>
            <td><span class="category">{{items.0.1.gitem.max_score|floatformat}}</span></td>
        </tr>

    {% endif %}

{% endfor %} {#iterate over the grades list#}
</table>

<span class="final-grade">Total grade, overall: {{total_grade|floatformat:1}}%</span>
<br>
<span class="category">To pass this course you must reach or exceed {{gradebook.passing_value|floatformat:1}}%</span>

{% endblock %}